### ISSUE TITLE
yarn v2 pnp support?

### ISSUE THREAD

**Issue by 3stacks** [contentful/create-contentful-app#79]
Hey team, I've recently begun the process of porting legacy extensions to apps (the extension sdk didn't seem to support pnp module either presumably due to some parcel errors under the hood: *note*: I haven't attempted to update those extensions, so if that's an option I'm open to that too).

After I initialised the contentful app with the cli, I ran yarn to switch it over to using pnp modules (we are in a big private workspace so I can't opt out of yarn) and installed + ran the app with `yarn start` I get the following error:

```
undefined
TypeScript error in undefined(undefined,undefined):
Cannot find type definition file for 'node'.  TS2688
```

I was originally getting the error with jest modules but it switched to this error when i removed the testing library stuff.

**Comment by merceyz** [comment]
It's a bug in `ts-pnp` that was fixed a long time ago in https://github.com/arcanis/ts-pnp/commit/66433e65cad9b1fbddac8349c352690c9c5f449a, the version create-react-app depends on is outdated and because they lock the version it wont update on its own. It was however updated in https://github.com/facebook/create-react-app/pull/8947 but they haven't released it yet.

You can force upgrade it using resolutions by applying this patch
```diff
diff --git a/package.json b/package.json
index 0501dad..deef55c 100644
--- a/package.json
+++ b/package.json
@@ -27,6 +27,9 @@
     "test": "react-scripts test",
     "eject": "react-scripts eject"
   },
+  "resolutions": {
+    "ts-pnp": "1.2.0"
+  },
   "eslintConfig": {
     "extends": "react-app"
   },

```

**Comment by Jwhiles** [comment]
Thanks @merceyz 

I'll leave this issue open for the time being, and close it once the change in create-react-app is released.
